#include "defines.h"

const uint NUM_SWITCHES = 16;
const uint SWITCHES[] = {
  SWITCH_CVBS_IN,     SWITCH_YC_IN,    SWITCH_YPBPR_OUT,    SWITCH_CVBS_OUT,
  SWITCH_LINE_DOUBLE, SWITCH_VASELINE, SWITCH_NOTCH_FILTER, SWITCH_FORCE_240P,
  SWITCH_B7,          SWITCH_B6,       SWITCH_B5,           SWITCH_B4,
  SWITCH_B3,          SWITCH_B2,       SWITCH_B1,           SWITCH_B0,
};

const uint NUM_FEATURE_SWITCHES = 8;
const uint FEATURE_SWITCHES[] = {
  SWITCH_CVBS_IN,     SWITCH_YC_IN,    SWITCH_YPBPR_OUT,    SWITCH_CVBS_OUT,
  SWITCH_LINE_DOUBLE, SWITCH_VASELINE, SWITCH_NOTCH_FILTER, SWITCH_FORCE_240P,
};

const uint NUM_BIT_SWITCHES = 8;
const uint BIT_SWITCHES[] = {
  SWITCH_B7, SWITCH_B6, SWITCH_B5, SWITCH_B4,
  SWITCH_B3, SWITCH_B2, SWITCH_B1, SWITCH_B0,
};

const uint NUM_TEST_REGISTERS = 1;
const device_register_t TEST_REGISTERS[] = {
  {0x20, 0xED},
};